project:
  type: website
  output-dir: docs

website:
  title: "Conditional-Probability-Exercise"
  sidebar:
    collapse-level: 1
    background: primary
    logo: "imgs/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/math4mad/conditional-prob-exercise
        text: GitHub
    style: docked
    
     
    
    contents:
      - href: index.qmd
        text: Home
      - section: "AFCP"
        contents: afcp-exercises/*
      - section : "Turing"
        contents: turing/*
      - section : "Basic"
        contents: basic/*
      - section : "Bayestheorem"
        contents: bayestheorem/*
      - section : "Logics"
        contents: logic/*

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

